Log link to build details, don't print JSON [CLOUDDST-2404]
release-engineering/pubtools-iib pull request #17
Opened 2020-11-10 14:43 UTC by neithere

The pubtools-iib CLI commands used to dump the build details JSON
into stdout. Pub would then call the commands, capture their stdout
and stderr output and add it to its own logs.

Such verbose output is unnecessary because the JSON is available
on the IIB server via HTTP API.

This PR removes the JSON from the logs and replaces it with the URL.

2020-11-10 16:26 UTC, midnightercz approved these changes

2020-11-10 18:06 UTC, neithere commented
@midnightercz has approved, could others PTAL too? @lipoja @emilyzheng @querti @chandwanitulsi @yashvardhannanavati
Thanks!

2020-11-10 22:00 UTC, rohanpm requested changes
Is there a need for a corresponding Pub change to prevent CI breaking there?

2020-11-11 18:59 UTC, neithere commented on pubtools/iib/iib_ops.py
>          sys.stderr.write("\n")
Thanks! Good catch. Removed.

2020-11-11 19:00 UTC, neithere commented on tests/test_iib_ops.py
> +    captured = capsys.readouterr()
You are right, that's better.

2020-11-11 19:05 UTC, neithere commented
> Is there a need for a corresponding Pub change to prevent CI breaking there?

None I'm aware of. AFAIK, Pub's integration tests mock the entry point, so the pubtools-iib's output seems to be covered only by its own unit tests. Is there anything else?

2020-11-11 19:08 UTC, neithere commented on pubtools/iib/iib_ops.py
>          sys.stderr.write("\n")
By the way, I hope it's OK that I mark those threads as resolved myself :)

2020-11-11 23:09 UTC, rohanpm commented
> AFAIK, Pub's integration tests mock the entry point, so the pubtools-iib's output seems to be covered only by its own unit tests. Is there anything else?

I don't know the answer, but CLOUDDST-2404 says one of the motivations is that, with the old approach, the Pub task log "contains full output of iib task which is also not desired as it can be changed easily and breaks pub CI".  And I remember something like that happening, but have not looked into whether this specific change is covering that incident exactly.

Something here wouldn't make sense if CLOUDDST-2404 on the one hand says "let's change the behavior because current behavior can break pub's CI" and on the other hand we're saying "this change will have no impact on Pub's CI", so I would have guessed that this indeed does affect the behavior of some test in Pub.

Regardless, I'm clicking Approve on this since it's not a problem with this PR as such.  But if it hasn't been looked into, it probably should be before releasing this.

2020-11-11 23:09 UTC, rohanpm approved these changes

2020-11-12 21:40 UTC, merged